name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^4.2.1
#  animated_text_kit: ^1.3.0
#  firebase_core: ^1.6.0
#  firebase_auth: ^3.1.1
#  cloud_firestore: ^2.5.3
  modal_progress_hud: ^0.1.3
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+4
  cloud_firestore: ^0.9.13+1
  http: ^0.12.1
  geolocator: ^5.3.1
  path_provider: ^1.6.28
  function_tree: ^0.8.12





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
